// ============================================================
// DATA.JS — Toàn bộ dữ liệu game
// Thêm game mới: copy một object, điền thông tin, đặt vào mảng GAMES
// ============================================================

const GAMES = [
  {
    id: 1,
    title: "Hollow Knight",
    genre: "action",
    desc: "Metroidvania kinh điển với thế giới ngầm tăm tối và đầy bí ẩn. Khám phá vương quốc côn trùng cổ đại Hallownest, chiến đấu với hàng trăm kẻ thù và boss độc đáo. Gameplay mượt mà, cốt truyện sâu sắc ẩn chứa trong từng góc khuất.",
    size: "9.1 GB",
    version: "1.5.78.11808",
    year: 2017,
    rating: 5.0,
    downloads: 84200,
    emoji: "🐛",
    genre_label: "Action / Metroidvania",
    badges: ["hot"],
    viet: true,
    download: "#",
    tags: ["Metroidvania", "Indie", "Khó"],
  },
  {
    id: 2,
    title: "Stardew Valley",
    genre: "simulation",
    desc: "Game nông trại huyền thoại do một người duy nhất tạo ra. Xây dựng trang trại từ mảnh đất hoang, kết bạn với dân làng Pelican Town, khám phá mỏ đầy quái vật và craft đồ vật. Thư giãn hoàn toàn.",
    size: "518 MB",
    version: "1.6.15",
    year: 2016,
    rating: 5.0,
    downloads: 120500,
    emoji: "🌾",
    genre_label: "Nông trại / RPG",
    badges: ["hot", "viet"],
    viet: true,
    download: "#",
    tags: ["Farming", "Thư giãn", "RPG"],
  },
  {
    id: 3,
    title: "Celeste",
    genre: "action",
    desc: "Platformer cực kỳ thử thách với câu chuyện cảm động về sức mạnh nội tâm. Leo lên đỉnh núi Celeste trong khi đối mặt với chính bản thân. Kiểm soát chính xác tuyệt vời, nhạc nền cực hay.",
    size: "1.2 GB",
    version: "1.4.0.0",
    year: 2018,
    rating: 4.9,
    downloads: 63100,
    emoji: "🏔️",
    genre_label: "Platformer / Indie",
    badges: ["new", "viet"],
    viet: true,
    download: "#",
    tags: ["Platformer", "Khó", "Cảm xúc"],
  },
  {
    id: 4,
    title: "Undertale",
    genre: "rpg",
    desc: "RPG nơi bạn không cần giết bất kỳ ai. Câu chuyện gây sốc và đầy nước mắt, nhạc nền iconic, và những khoảnh khắc bất ngờ sẽ khiến bạn nhớ mãi. Mỗi quyết định đều có hậu quả.",
    size: "210 MB",
    version: "1.08",
    year: 2015,
    rating: 4.9,
    downloads: 97300,
    emoji: "❤️",
    genre_label: "RPG / Indie",
    badges: ["hot", "viet"],
    viet: true,
    download: "#",
    tags: ["RPG", "Indie", "Cốt truyện"],
  },
  {
    id: 5,
    title: "Hades",
    genre: "action",
    desc: "Roguelite action nơi bạn đóng vai con trai thần chết Zagreus, liên tục vượt ngục giới. Mỗi lần chết là một lần cốt truyện tiến thêm. Gameplay combat siêu mướt, replayability vô tận.",
    size: "3.1 GB",
    version: "1.38388",
    year: 2020,
    rating: 4.9,
    downloads: 88700,
    emoji: "⚔️",
    genre_label: "Roguelite / Action",
    badges: ["hot"],
    viet: false,
    download: "#",
    tags: ["Roguelite", "Action", "Mythology"],
  },
  {
    id: 6,
    title: "Disco Elysium",
    genre: "rpg",
    desc: "RPG thuần đối thoại không có combat. Bạn là thám tử mất trí nhớ điều tra vụ án giết người. Thế giới Revachol cực kỳ phong phú, hệ thống skill đặc biệt, viết lách xuất sắc nhất làng game.",
    size: "15 GB",
    version: "Final Cut",
    year: 2019,
    rating: 4.8,
    downloads: 41200,
    emoji: "🕵️",
    genre_label: "RPG / Detective",
    badges: ["viet"],
    viet: true,
    download: "#",
    tags: ["RPG", "Detective", "Cốt truyện"],
  },
  {
    id: 7,
    title: "Into the Breach",
    genre: "strategy",
    desc: "Tactics game turn-based được thiết kế hoàn hảo từng pixel. Điều khiển mech bảo vệ nhân loại khỏi Vek. Mỗi màn chơi là một câu đố chiến thuật, không có yếu tố may rủi. Từ nhà làm FTL.",
    size: "298 MB",
    version: "1.2.86",
    year: 2018,
    rating: 4.8,
    downloads: 39500,
    emoji: "🤖",
    genre_label: "Chiến thuật / Turn-based",
    badges: [],
    viet: false,
    download: "#",
    tags: ["Turn-based", "Chiến thuật", "Indie"],
  },
  {
    id: 8,
    title: "Sekiro: Shadows Die Twice",
    genre: "action",
    desc: "Action RPG cực khó của FromSoftware đặt tại Nhật Bản thời Sengoku. Hệ thống posture và parry độc đáo đòi hỏi phản xạ chính xác. Cảm giác chiến thắng boss cực kỳ thỏa mãn.",
    size: "14.3 GB",
    version: "1.06",
    year: 2019,
    rating: 4.9,
    downloads: 72100,
    emoji: "🗡️",
    genre_label: "Action RPG / Soulslike",
    badges: ["hot"],
    viet: false,
    download: "#",
    tags: ["Soulslike", "Khó", "Samurai"],
  },
  {
    id: 9,
    title: "Elden Ring",
    genre: "rpg",
    desc: "Masterpiece của FromSoftware kết hợp với George R.R. Martin. Open world Soulslike rộng lớn với hàng trăm giờ khám phá. Xây dựng nhân vật tự do, lore cực kỳ sâu sắc.",
    size: "44.5 GB",
    version: "1.12.3",
    year: 2022,
    rating: 5.0,
    downloads: 156000,
    emoji: "👑",
    genre_label: "Open World / Soulslike",
    badges: ["hot", "new"],
    viet: false,
    download: "#",
    tags: ["Open World", "Soulslike", "RPG"],
  },
  {
    id: 10,
    title: "Tetris Effect: Connected",
    genre: "puzzle",
    desc: "Tetris được tái sinh với âm thanh và hình ảnh ảo diệu. Mỗi xoay block đồng bộ với nhạc tạo ra trải nghiệm gần như thiền định. Mode multiplayer Connected hoàn toàn mới lạ.",
    size: "3.8 GB",
    version: "1.2.1",
    year: 2021,
    rating: 4.7,
    downloads: 28900,
    emoji: "🎯",
    genre_label: "Puzzle / Music",
    badges: ["new"],
    viet: false,
    download: "#",
    tags: ["Puzzle", "Âm nhạc", "Thư giãn"],
  },
  {
    id: 11,
    title: "Vampire Survivors",
    genre: "action",
    desc: "Rogue-like auto-shooter cực kỳ gây nghiện. Chọn vũ khí, upgrade, sống sót qua màn đêm dài. Đơn giản nhưng độ sâu vô tận. Game 5 đô gây sốt cộng đồng Steam năm 2022.",
    size: "520 MB",
    version: "1.10.101",
    year: 2022,
    rating: 4.7,
    downloads: 94200,
    emoji: "🧛",
    genre_label: "Roguelite / Survival",
    badges: ["hot", "new"],
    viet: true,
    download: "#",
    tags: ["Roguelite", "Gây nghiện", "Indie"],
  },
  {
    id: 12,
    title: "Firewatch",
    genre: "adventure",
    desc: "Walking simulator đầy cảm xúc trong rừng núi Wyoming năm 1989. Henry trốn tránh quá khứ bằng công việc gác rừng và dần khám phá bí ẩn. Đồ họa hand-painted tuyệt đẹp, diễn xuất voice acting chuẩn.",
    size: "3.2 GB",
    version: "1.10",
    year: 2016,
    rating: 4.5,
    downloads: 31700,
    emoji: "🔥",
    genre_label: "Adventure / Story",
    badges: [],
    viet: true,
    download: "#",
    tags: ["Walking Sim", "Cốt truyện", "Thư giãn"],
  },
  {
    id: 13,
    title: "The Witcher 3: Wild Hunt",
    genre: "rpg",
    desc: "RPG open world đặt chuẩn vàng của thể loại. Geralt of Rivia tìm con gái nuôi trong thế giới fantasy đen tối. Side quest chất lượng không thua main quest, hệ thống lựa chọn ảnh hưởng thực sự.",
    size: "50.2 GB",
    version: "4.04 GOTY",
    year: 2015,
    rating: 5.0,
    downloads: 198000,
    emoji: "🐺",
    genre_label: "Open World RPG",
    badges: ["hot", "viet"],
    viet: true,
    download: "#",
    tags: ["Open World", "RPG", "Fantasy"],
  },
  {
    id: 14,
    title: "Cuphead",
    genre: "action",
    desc: "Run & gun cực khó được vẽ tay theo phong cách hoạt hình 1930s. Mỗi boss là một màn chơi độc lập với pattern phức tạp. Art style không nơi nào có, nhạc jazz big band tuyệt vời.",
    size: "2.8 GB",
    version: "1.3.4",
    year: 2017,
    rating: 4.7,
    downloads: 58400,
    emoji: "☕",
    genre_label: "Run & Gun / Boss Rush",
    badges: ["viet"],
    viet: true,
    download: "#",
    tags: ["Boss Rush", "Khó", "Phong cách"],
  },
  {
    id: 15,
    title: "Dead Cells",
    genre: "action",
    desc: "Roguelite Metroidvania kết hợp hoàn hảo. Mỗi run là một trải nghiệm mới với vũ khí ngẫu nhiên và build phong phú. Combat cực kỳ mượt mà và có chiều sâu. DLC liên tục cập nhật thêm nội dung.",
    size: "1.5 GB",
    version: "3.5 GOTY",
    year: 2018,
    rating: 4.8,
    downloads: 67800,
    emoji: "💀",
    genre_label: "Roguelite / Metroidvania",
    badges: ["hot"],
    viet: false,
    download: "#",
    tags: ["Roguelite", "Metroidvania", "Khó"],
  },
  {
    id: 16,
    title: "Resident Evil Village",
    genre: "horror",
    desc: "Survival horror first-person kết hợp action. Ethan Winters tìm con gái trong ngôi làng đầy quái vật. Lady Dimitrescu trở thành biểu tượng văn hóa. Gameplay tight, atmosphere rùng rợn.",
    size: "28.9 GB",
    version: "1.51",
    year: 2021,
    rating: 4.6,
    downloads: 52300,
    emoji: "🏰",
    genre_label: "Horror / Action",
    badges: ["new"],
    viet: true,
    download: "#",
    tags: ["Horror", "FPS", "Story"],
  },
  {
    id: 17,
    title: "Subnautica",
    genre: "adventure",
    desc: "Survival game dưới đáy đại dương hành tinh xa lạ. Xây dựng căn cứ dưới nước, khám phá vùng biển sâu thẳm đầy sinh vật kỳ lạ. Cảm giác sợ hãi và tò mò xen lẫn nhau liên tục.",
    size: "8.4 GB",
    version: "68598",
    year: 2018,
    rating: 4.8,
    downloads: 71200,
    emoji: "🌊",
    genre_label: "Survival / Exploration",
    badges: [],
    viet: true,
    download: "#",
    tags: ["Survival", "Khám phá", "Underwater"],
  },
  {
    id: 18,
    title: "Cyberpunk 2077",
    genre: "rpg",
    desc: "Open world RPG trong thành phố dystopia Night City đầy neon. Sau các bản vá lỗi, game đã trở thành một trong những RPG tốt nhất. DLC Phantom Liberty được khen ngợi cực cao.",
    size: "70.1 GB",
    version: "2.12 + Phantom Liberty",
    year: 2020,
    rating: 4.6,
    downloads: 143000,
    emoji: "🌃",
    genre_label: "Open World RPG / Cyberpunk",
    badges: ["hot", "new"],
    viet: true,
    download: "#",
    tags: ["Open World", "Cyberpunk", "RPG"],
  },
  {
    id: 19,
    title: "Terraria",
    genre: "action",
    desc: "Sandbox 2D với nội dung không giới hạn. Đào đất, xây nhà, đánh boss, craft gear, khám phá hầm ngục. Hơn 400 boss và kẻ thù, hàng nghìn item. Đã chơi hàng trăm giờ mà vẫn còn thứ để khám phá.",
    size: "1.1 GB",
    version: "1.4.4.9",
    year: 2011,
    rating: 4.9,
    downloads: 205000,
    emoji: "⛏️",
    genre_label: "Sandbox / Action",
    badges: ["hot"],
    viet: true,
    download: "#",
    tags: ["Sandbox", "Craft", "Multiplayer"],
  },
  {
    id: 20,
    title: "Portal 2",
    genre: "puzzle",
    desc: "Puzzle game kinh điển dùng súng tạo portal. Cốt truyện hài hước đỉnh cao với GLaDOS, Wheatley. Cả campaign đơn lẫn co-op đều tuyệt vời. Một trong những game được đánh giá cao nhất mọi thời đại.",
    size: "9.8 GB",
    version: "1.0",
    year: 2011,
    rating: 5.0,
    downloads: 178000,
    emoji: "🌀",
    genre_label: "Puzzle / FPS",
    badges: ["hot", "viet"],
    viet: true,
    download: "#",
    tags: ["Puzzle", "Co-op", "Classic"],
  },
];

// Genre metadata
const GENRES = [
  { id: "action",     icon: "⚔️",  name: "Action",        desc: "Hành động nhanh, chiến đấu mượt" },
  { id: "rpg",        icon: "🧙",  name: "RPG",           desc: "Nhập vai, cốt truyện, phát triển nhân vật" },
  { id: "strategy",   icon: "♟️",  name: "Chiến thuật",   desc: "Suy nghĩ kỹ trước mỗi bước đi" },
  { id: "puzzle",     icon: "🧩",  name: "Đố trí",        desc: "Giải câu đố, động não" },
  { id: "shooter",    icon: "🔫",  name: "Bắn súng",      desc: "FPS/TPS hành động" },
  { id: "adventure",  icon: "🗺️",  name: "Phiêu lưu",    desc: "Khám phá thế giới rộng lớn" },
  { id: "simulation", icon: "🏗️",  name: "Mô phỏng",     desc: "Xây dựng, quản lý, nông trại" },
  { id: "horror",     icon: "👻",  name: "Kinh dị",       desc: "Rùng rợn, hồi hộp" },
];
